/**
 * firebase.ts
 *
 * Central Firebase configuration module. Initialises the Firebase app, Auth,
 * and Firestore instances and re-exports all SDK helpers used throughout the
 * application so that other modules only need to import from this single file.
 */

import { initializeApp } from 'firebase/app';
import { 
  getAuth, 
  GoogleAuthProvider, 
  signInWithPopup, 
  signOut, 
  onAuthStateChanged,
  createUserWithEmailAndPassword,
  signInWithEmailAndPassword,
  updateProfile,
  sendPasswordResetEmail
} from 'firebase/auth';
import {
  getFirestore,
  collection,
  doc,
  getDoc,
  getDocs,
  setDoc,
  addDoc,
  deleteDoc,
  onSnapshot,
  query,
  where,
  orderBy,
  limit,
  getDocFromServer,
  writeBatch,
  increment
} from 'firebase/firestore';
import firebaseConfig from '../firebase-applet-config.json';

// ─── SDK Initialisation ────────────────────────────────────────────────────
// The config object is loaded from the JSON file generated by the Firebase
// project setup. Keep that file out of version control if it contains secrets.
const app = initializeApp(firebaseConfig);

/** Firestore database instance — used for all data reads and writes. */
export const db = getFirestore(app);

/** Firebase Auth instance — manages user sessions. */
export const auth = getAuth(app);

/** Pre-configured Google OAuth provider used for one-click sign-in. */
export const googleProvider = new GoogleAuthProvider();

// ─── Connectivity Check ───────────────────────────────────────────────────
// Attempts a server-side read on app start to detect offline/misconfiguration
// early. The 'test/connection' document need not exist; the request itself
// validates connectivity. Errors are logged but do not crash the app.
async function testConnection() {
  try {
    await getDocFromServer(doc(db, 'test', 'connection'));
  } catch (error) {
    if (error instanceof Error && error.message.includes('the client is offline')) {
      console.error("Please check your Firebase configuration. The client is offline.");
    }
  }
}
testConnection();

// ─── Re-exports ────────────────────────────────────────────────────────────
// All Firebase SDK functions used in the app are re-exported here so
// consumers import from './firebase' rather than directly from Firebase packages.
export { 
  signInWithPopup, 
  signOut, 
  onAuthStateChanged,
  createUserWithEmailAndPassword,
  signInWithEmailAndPassword,
  updateProfile,
  sendPasswordResetEmail,
  collection, 
  doc, 
  getDoc, 
  getDocs, 
  setDoc, 
  addDoc,
  deleteDoc, 
  onSnapshot, 
  query, 
  where, 
  orderBy, 
  limit,
  writeBatch,
  increment
};
